### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'module'

### ISSUE THREAD

**Issue by woshishui1** [Syencil/mobile-yolov5-pruning-distillation#20]
test.py文件使用剪枝后的模型会报错，报错信息如下：
Traceback (most recent call last):
File "/home/demon/PycharmProjects/mobile-yolov5-pruning-distillation/test.py", line 357, in
test(opt.data,
File "/home/demon/PycharmProjects/mobile-yolov5-pruning-distillation/test.py", line 89, in test
names = {k: v for k, v in enumerate(model.names if hasattr(model, 'names') else model.module.names)}
File "/home/demon/anaconda3/envs/pytorch_gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in getattr
raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'module'

**Comment by deleike410** [comment]
same  issue..
Traceback (most recent call last):
  File "test.py", line 358, in <module>
    test(opt.data,
  File "test.py", line 90, in test
    names = {k: v for k, v in enumerate(model.names if hasattr(model, 'names') else model.module.names)}
  File "/home/sq/.pyenv/versions/my-distill-yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'names'

**Comment by johnsonkao0213** [comment]
我也有遇到

**Comment by Syencil** [comment]
参考 #38

**Comment by ResidualNS** [comment]
I also meet the error when I run yolo5s:
Traceback (most recent call last):
  File "test.py", line 365, in <module>
    test(opt.data,
  File "test.py", line 97, in test
    names = {k: v for k, v in enumerate(model.names if hasattr(model, 'names') else model.module.names)}
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'names'

I already use the command export PYTHONPATH=$PWD.
