### ISSUE TITLE
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by yao-zheng-yi** [Syencil/mobile-yolov5-pruning-distillation#29]
你好，我尝试使用yolov5s作为模型进行训练，命令行为
`python train.py --type vocs`
但是在训练完1个epoch后测试验证集时，报错

Traceback (most recent call last):
  File "train.py", line 802, in <module>
    train(hyp)
  File "train.py", line 453, in train
    results, maps, times = test.test(opt.data,
  File "/home/cwy/mobile-yolov5-pruning-distillation/test.py", line 112, in test
    inf_out, train_out = model(img, augment=augment)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 621, in forward
    outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cwy/mobile-yolov5-pruning-distillation/models/yolo.py", line 94, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/cwy/mobile-yolov5-pruning-distillation/models/yolo.py", line 111, in forward_once
    x = m(x)  # run
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cwy/mobile-yolov5-pruning-distillation/models/common.py", line 86, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cwy/mobile-yolov5-pruning-distillation/models/common.py", line 21, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/cwy/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

尝试了很多方法，但还是报同样的错误，想请教一下该如何解决？

**Comment by yao-zheng-yi** [comment]
@Syencil 你好，这个问题我还是没有解决，能请教一下你有什么思路吗

**Comment by Syencil** [comment]
model.float()
