### ISSUE TITLE
Thanks for your fantastic work!  But  I  encountered a problem:  onnx export error...

### ISSUE THREAD

**Issue by Byronnar** [Syencil/mobile-yolov5-pruning-distillation#30]
###      env :
 ubuntu1804
 torch: 1.6.0 
 torchvision: 0.7.0 
 Training:    python3 train.py --type vocs   python3 train.py --type dmvocs
 export:       export PYTHONPATH="$PWD" && python models/onnx_export.py --weights  outputs/dmvocs/weights/best_dmvocs.pt --img 640 --batch 1

Error:
```
Namespace(batch_size=1, img_size=[640], weights='outputs/dmvocs/weights/best_dmvocs.pt')
Fusing layers...
Model Summary: 148 layers, 3.59629e+06 parameters, 3.31818e+06 gradients
Traceback (most recent call last):
  File "models/onnx_export.py", line 35, in <module>
    _ = model(img)  # dry run
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/byronnar/mobile-yolov5-pruning-distillation/models/yolo.py", line 94, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/data/byronnar/mobile-yolov5-pruning-distillation/models/yolo.py", line 111, in forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/byronnar/mobile-yolov5-pruning-distillation/models/common.py", line 24, in fuseforward
    return self.act(self.conv(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 3, 3, 3], but got 3-dimensional input of size [1, 3, 640] instead
```
How can I solve this problem? Looking forward to your reply! Thank you!

**Comment by Byronnar** [comment]
Using origin yolov5 export code is work! Thank you!
